[package]
name = "rust_google_tasks"
version = "0.2.1"
authors = ["Siamion Makarski <s.makarski.s@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
chrono = { version = "^0.4.0", features = ["serde"]}
serde = "^1.0"
serde_json = "^1.0"
serde_derive = "^1.0"
serde_urlencoded = "^0.6.0"
reqwest = "^0.9.0"
